export * from './space.js'
export * from './controller.js'
export * from './hand.js'
export * from './mesh.js'
export * from './plane.js'
export * from './pointer.js'
export * from './guard/index.js'
export * from './hooks.js'
export * from './input.js'
export * from './default.js'
export * from './xr.js'
export * from './origin.js'
export * from './teleport.js'
export * from './hit-test.js'
export * from './anchor.js'
export * from './dom-overlay.js'
export * from './layer.js'
export * from './controller-locomotion.js'
export * from './events.js'

//react-three/xr v5 compatibility layer
export * from './deprecated/index.js'

export { isAppleVisionPro } from '@pmndrs/xr'
