/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 WebXRSpaces.glb --transform -t 
Files: WebXRSpaces.glb [88.37KB] > /Users/kaileanokeefe/Desktop/WebXRSpaces-transformed.glb [10.58KB] (88%)
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'
import * as THREE from 'three'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type GLTFResult = GLTF & {
  nodes: {
    Dude: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
}

export function DemoDude(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/WebXRSpaces-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Dude.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('/WebXRSpaces-transformed.glb')
