/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/door.glb -t 
Author: witnessk (https://sketchfab.com/witnessk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/door-with-frame-2f2f149f3ec44d658a02c1f924dfa449
Title: Door with frame
*/

import { Mesh, MeshStandardMaterial } from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'
import { Handle, HandleTarget } from '@react-three/handle'

type GLTFResult = GLTF & {
  nodes: {
    Plane003_Door_0: Mesh
    Circle002_Glossy_0: Mesh
    Plane001_Glossy_0: Mesh
    Plane001_Door_0: Mesh
    Plane002_Glossy_0: Mesh
    Plane002_Door_0: Mesh
  }
  materials: {
    Door: MeshStandardMaterial
    Glossy: MeshStandardMaterial
  }
}

export function Door(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/door.glb') as any as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group position={[-0.435, -0.101, 0.249]}>
          <HandleTarget>
            <mesh geometry={nodes.Plane001_Glossy_0.geometry} material={materials.Glossy} />
            <mesh geometry={nodes.Plane001_Door_0.geometry} material={materials.Door} />
            <mesh
              geometry={nodes.Plane003_Door_0.geometry}
              material={materials.Door}
              position={[0.852, 0.017, 0.782]}
            />
            <Handle targetRef="from-context" translate="as-rotate" rotate={{ x: false, y: false, z: [-Math.PI, 0] }}>
              <group position={[0.81, 0.043, 0.803]}>
                <Handle
                  stopPropagation={false}
                  translate={false}
                  scale={false}
                  rotate={{ x: false, y: [-Math.PI / 2, 0], z: false }}
                >
                  <mesh geometry={nodes.Circle002_Glossy_0.geometry} material={materials.Glossy} />
                </Handle>
              </group>
            </Handle>
          </HandleTarget>
        </group>
        <mesh geometry={nodes.Plane002_Glossy_0.geometry} material={materials.Glossy} />
        <mesh geometry={nodes.Plane002_Door_0.geometry} material={materials.Door} />
      </group>
    </group>
  )
}

useGLTF.preload('/door.glb')
